Repository jreleaser/jreleaser, pull requests merged in 2022-11, with the labels that each got.

#1011 docs: Fix link in README.md [skip ci]
  README.adoc
Labels: build

#1043 fix: Detect title of commits with both line ending
  sdks/jreleaser-git-java-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java
  sdks/jreleaser-git-java-sdk/src/test/java/org/jreleaser/sdk/git/ChangelogGeneratorUnitTest.java
Labels: bug

#1027 Add support threaded statuses in Mastodon
  api/jreleaser-model-api/src/main/java/org/jreleaser/model/api/announce/MastodonAnnouncer.java
  api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties
  api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages_ca.properties
  api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages_ko.properties
  api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages_ru.properties
  core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/announce/MastodonAnnouncer.java
  core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/announce/MastodonAnnouncerValidator.java
  plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/dsl/announce/MastodonAnnouncer.groovy
  plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/dsl/announce/MastodonAnnouncerImpl.groovy
  sdks/jreleaser-mastodon-java-sdk/jreleaser-mastodon-java-sdk.gradle
  sdks/jreleaser-mastodon-java-sdk/src/main/java/org/jreleaser/sdk/mastodon/MastodonAnnouncer.java
  sdks/jreleaser-mastodon-java-sdk/src/main/java/org/jreleaser/sdk/mastodon/MastodonSdk.java
  sdks/jreleaser-mastodon-java-sdk/src/main/java/org/jreleaser/sdk/mastodon/api/MastodonAPI.java
  sdks/jreleaser-mastodon-java-sdk/src/main/java/org/jreleaser/sdk/mastodon/api/Status.java
  sdks/jreleaser-mastodon-java-sdk/src/test/java/org/jreleaser/sdk/mastodon/MastodonSdkTest.java
  sdks/jreleaser-mastodon-java-sdk/src/test/java/org/jreleaser/sdk/mastodon/WireMockExtension.java
Labels: enhancement, hackergarten
