Repository jreleaser/jreleaser, pull requests merged in 2022-10, with the labels that each got.

#985 build: Update use of set-output in workflows
  .github/workflows/early-access.yml
  .github/workflows/release.yml
  .github/workflows/smoke-tests-ant.yml
  .github/workflows/smoke-tests-cli.yml
  .github/workflows/smoke-tests-gradle.yml
  .github/workflows/smoke-tests-maven.yml
  core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/binary/appimage/.github/workflows/release.yml.tpl
  core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-binary/appimage/.github/workflows/release.yml.tpl
  core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/jlink/appimage/.github/workflows/release.yml.tpl
  core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/native-image/appimage/.github/workflows/release.yml.tpl
  src/jreleaser/distributions/jreleaser-standalone/appimage/.github/workflows/release.yml.tpl
Labels: Hacktoberfest, hacktoberfest-accepted, build

#990 feat(announce): Add discourse sdk
  .vscode/settings.json
  api/jreleaser-model-api/src/main/java/org/jreleaser/model/api/announce/Announce.java
  api/jreleaser-model-api/src/main/java/org/jreleaser/model/api/announce/DiscourseAnnouncer.java
  core/jreleaser-engine/jreleaser-engine.gradle
  core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/JReleaserSupport.java
  core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/announce/Announce.java
  core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/announce/DiscourseAnnouncer.java
  core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/announce/AnnouncersValidator.java
  core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/announce/DiscourseAnnouncerValidator.java
  core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/announcers/discourse.tpl
  sdks/jreleaser-discourse-java-sdk/gradle.properties
  sdks/jreleaser-discourse-java-sdk/jreleaser-discourse-java-sdk.gradle
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/DiscourseAnnouncer.java
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/DiscourseAnnouncerBuilder.java
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/DiscourseAnnouncerBuilderFactory.java
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/DiscourseException.java
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/DiscourseSdk.java
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/ActionsSummary.java
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/Category.java
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/CategoryList.java
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/CategoryResponse.java
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/DiscourseAPI.java
  sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/Post.java
  sdks/jreleaser-discourse-java-sdk/src/test/java/org/jreleaser/sdk/discourse/ApiEndpoints.java
  sdks/jreleaser-discourse-java-sdk/src/test/java/org/jreleaser/sdk/discourse/DiscoursePostTest.java
  sdks/jreleaser-discourse-java-sdk/src/test/java/org/jreleaser/sdk/discourse/Stubs.java
  sdks/jreleaser-discourse-java-sdk/src/test/java/org/jreleaser/sdk/discourse/WireMockExtension.java
Labels: enhancement

#1000 i18n: Fix Italian translation of CLI resources.
  plugins/jreleaser/src/main/resources/org/jreleaser/cli/Messages_it.properties
Labels: cli, translation
