Repository jreleaser/jreleaser, pull requests merged in 2022-08, with the labels that each got.

#914 feat(changelog): Add warning when creating a changelog of shallow copy
  .gitignore
  core/jreleaser-utils/src/main/resources/org/jreleaser/bundle/Messages.properties
  sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java
  sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/GitSdk.java
Labels: enhancement

#924 fix: `projectNameCapitalized` now handles hyphens as spaces
  core/jreleaser-model/src/main/java/org/jreleaser/model/GitService.java
  core/jreleaser-model/src/main/java/org/jreleaser/model/JReleaserModel.java
  core/jreleaser-model/src/main/java/org/jreleaser/model/Project.java
  core/jreleaser-model/src/test/java/org/jreleaser/model/JReleaserModelTest.java
  core/jreleaser-utils/src/main/java/org/jreleaser/util/StringUtils.java
Labels: bug

#932 i18n: Update Italian translation of CLI resources
  apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages.properties
  apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages_it.properties
Labels: cli, translation
